### ISSUE TITLE
Design Form Page with repo name and it's link

### ISSUE THREAD

**Issue by Nishu0** [clubgamma/Good_First_Issue_Web_App#10]
Form Page for Adding the list of the following things
Name of new repo, link of the repo and it's good first issue small description along with it. 
Also add option to add the languages used to resolve the issue. 
It should be made so it should follow light and dark mode both.

**Comment by hemantgarg1452** [comment]
Hey @Nishu0 I want to contribute to this issue. please assign this task to me.

**Comment by alaykabir** [comment]
Hey @Nishu0, I am interested in working on this project. Can you please assign this to me and mention what should be done in the About us page?

**Comment by Nishu0** [comment]
Hey @alaykabir @hemantgarg1452 sorry for the late reply you need to design a form page on which organizations can add their issues description and link along with the Tech Stack Language needed to resolve the issue. Let me know if you still want to contribute I will assign the issue

**Comment by alaykabir** [comment]
Hey @Nishu0  I want to contribute. I have understood the task and I am willing to work. Please assign me the issue.

**Comment by Nishu0** [comment]
@alaykabir 
You can start working I have assigned this issue to you. Make sure to follow Contributing Guidelines.
