### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by Nishu0** [clubgamma/Good_First_Issue_Web_App#16]
**Pls Use the Logo from the repo it is already designed and design kit is available**
Simple and Modern Looking Landing Page which contains all the information about Project. 

Tasks

- Navbar
- What is GFI Section
- Motivation for the Project Section
- How to Contribute Section (Simple Steps Process)
- Footer (with Repo Link)

Make Sure to create a Attractive and Simple Page.

**Comment by bhavya2021245** [comment]
Can I do this?

**Comment by Nishu0** [comment]
@bhavya2021245 
You can start working I have assigned this issue to you. Make sure to follow Contributing Guidelines.

**Comment by mohdahsanrazakhan** [comment]
@Nishu0 do you mean. Replacing this https://good-first-issue-web-app.vercel.app/ user interface into your above given tasks. Right?

**Comment by Nishu0** [comment]
@mohdahsanrazakhan Yes

**Comment by mohdahsanrazakhan** [comment]
Ok @Nishu0 , I am trying to reform this page completely, according to your tasks.
