### ISSUE TITLE
Create a Home Page which contains list of GFI Links with Project Name

### ISSUE THREAD

**Issue by Nishu0** [clubgamma/Good_First_Issue_Web_App#3]
Simple Home Page with which contains list of GFI Links with Project Name(Dummy Page is fine Backend Issue is  already there created)

**Comment by shrutilenka** [comment]
Hey @Nishu0, I am interested in working on this project. Can you briefly mention what needs to be put on the home page?

**Comment by Nishu0** [comment]
@shrutilenka Simple Home Page Design Contains the list of the following things
1. Repo Name with count of good first issue.
2. Tags of the languages used in the project.
3. Filter the repo by languages.

**Comment by notpx** [comment]
This is closed? Or still open? Cause I can make a good page
