### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by Nishu0** [clubgamma/Good_First_Issue_Web_App#5]
Create a Simple About US page which contains the link of Github Repo and Contains the Contributors names

**Comment by syprogrammer** [comment]
hi i have required knowledge of web development please assign it to me

**Comment by Nishu0** [comment]
You can start Working I have Assigned this issue to you. Make sure to follow Contributing Guidelines.

**Comment by syprogrammer** [comment]
Do i have to write name of every repositories and there contributors from your profile
Here is the design i have made is it ok : [https://bit.ly/3RQUGNg](url)

**Comment by Nishu0** [comment]
Great Work. Create a PR with Detail Description of your work and add the below 2 lines in the description. It is compulsory for sucessful submission.

- [x] I have read the Code Of Conduct.

- [x] I have followed all the steps of submission properly.

**Comment by nancyKasaudhan20** [comment]
Hey, I am a frontend developer. Pls assign me this task.
