### ISSUE TITLE
Create Good First Issue Logo 

### ISSUE THREAD

**Issue by Nishu0** [clubgamma/Good_First_Issue_Web_App#6]
Provide at least two logos for Good First Issue Web App.

**Comment by abhinaba-dash** [comment]
@Nishu0 I am a graphic designer and I want to work on this issue , please assign it to me. You can check out my logo works here [(https://drive.google.com/drive/u/0/folders/1vz6ujDU52T3oYx5oqcz2_yjqdBy5x_FP)](https://drive.google.com/drive/u/0/folders/1vz6ujDU52T3oYx5oqcz2_yjqdBy5x_FP) and also you can checkout my behance portfolio here [https://www.behance.net/abhinabdash1](https://www.behance.net/abhinabdash1)

**Comment by Nishu0** [comment]
Great Work. 
You can start working I have assigned this issue to you. Make sure to follow Contributing Guidelines.

**Comment by abhinaba-dash** [comment]
@Nishu0 
I have come up with many colour variations of both the logos. Please have a look on this two and respond me which colour variation of which logo you like, so that I can give you the png folders of the same. 
![logo 1](https://user-images.githubusercontent.com/114768158/194891023-40c6146f-5243-42bd-9a01-dcf13a61817d.png)
![logo 2](https://user-images.githubusercontent.com/114768158/194891047-0b067ffb-2c6d-4be0-8053-c9a19a1aa573.png)

**Comment by Nishu0** [comment]
@abhinaba-dash 
This is great work and I really like both the design but I like to for the Logo 2 variation because it will look great in mobile and laptop according the design size of it. I like to go with the variation of the back and white where letter 'i' is in blue to match the dark and light mode. (Colour code for black : #006086 and for white the highlighted displayed one in Logo 2). Also add the concept design it will create impact to understand the logo designing and the depth you take to make it.

Create a PR with Detail Description of your work and add the below 2 lines in the description. It is compulsory for successful submission.

- [x] I have read the Code Of Conduct.

- [x] I have followed all the steps of submission properly.

**Comment by abhinaba-dash** [comment]
@Nishu0 
Thank you for your appreciation. Sorry but I got confused which logo do you choose ? 
1. Where background is black and writing part is white with i in blue or
2. Where background is white and writing part is black with i in blue or
3. You want both 1 & 2 for dark and light mode 
Note that the colour which I used in dark background is different from the blue colour that I used in light mode.
And yes I will make one concept design with it on a separate file.

**Comment by Nishu0** [comment]
@abhinaba-dash 
3. I want both 1 and 2 for dark and light mode where writing part is white and black with i in blue. I liked both different background it shades is great along with dark and light mode.
